### ISSUE TITLE
Minor documentation error

### ISSUE THREAD

**Issue by pjacklam** [sisyphus/math-fakedd#1]
The section "TRANSCENDENTAL FUNCTIONS" in the documentation says

```
  Return (respectively) pi (3.141...), Euler's constant (0.577...)
  and Catalan's constant (0.577...) .
```
However, Catalan’s constant is 0.915965…

PS. Thanks for the writing Math::FakeDD! I’ve had fun playing with it.

**Comment by sisyphus** [comment]
Thanks @pjacklam .
Now fixed in github (https://github.com/sisyphus/math-fakedd/commit/5c141d59c17a8245081c9b911316f7cbe30bd91a).

I find the DoubleDouble to be an intriguing little beast . (I'm not sure whether emphasis should be on "intriguing" or on "beast" ;-)
The only hardware I have that supports it is a couple of bigendian Mac ppc64 (G5) machines - one of which is running Debian Wheezy, which is well past EOL.
The other still has its original Apple system on it, and I'm not interested in running that system at all.

It's hard to find modern systems that will work on those old machines.
At least, I'm having trouble finding a modern system that caters for them.
(If you know of one, please tell me.)

Cheers,
Rob
